name: Build Dependencies
description: Builds dependencies for obs-deps with specified architecture, type, and build config
inputs:
  target:
    description: Build target for dependencies
    required: true
  type:
    description: Build type (shared or static libraries)
    required: false
    default: static
  config:
    description: Build configuration
    required: false
    default: Release
  workingDirectory:
    description: Working directory for repository action
    required: false
    default: ${{ github.workspace }}
runs:
  using: composite
  steps:
    - name: Build and Install Dependencies
      if: runner.os == 'macOS'
      shell: zsh --no-rcs --errexit --pipefail {0}
      run: |
        : Build macOS Dependencies

        ./build-deps.zsh \
          --target ${{ inputs.target }} \
          --config ${{ inputs.config }} \
          --${{ inputs.type }}

    - name: Build and Install Dependencies
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        # Build Windows Dependencies

        $Params = @{
          Target = '${{ inputs.target }}'
          Configuration = '${{ inputs.config }}'
          Shared = $(if ( '${{ inputs.type }}' -eq 'shared' ) { $true } else { $false })
        }

        ./Build-Dependencies.ps1 @Params